### ISSUE TITLE
The unhandled exception in akka.net framework from mono

### ISSUE THREAD

**Issue by Alexcei88** [helios-io/helios#129]
I am using akka.net framework for building actor model. I caught next unhandled exception

> System.NullReferenceException: Object reference not set to an instance of an object
> at Helios.Concurrency.DedicatedThreadPool+ThreadPoolWorkQueue+d__9.MoveNext () [0x00000] in :0
> at Helios.Concurrency.DedicatedThreadPool+PoolWorker.RunThread () [0x00000] in :0
> at System.Threading.Thread.StartInternal () [0x00000] in :0
> 

_Linux version 4.2.0-42-generic (buildd@lgw01-55) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu114.04.3) ) #4914.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016_

_Mono version 4.0.5.1_

**Comment by Alexcei88** [comment]
I am using akka.net framework for building actor model. I caught next unhandled exception

System.NullReferenceException: Object reference not set to an instance of an object
  at Helios.Concurrency.DedicatedThreadPool+ThreadPoolWorkQueue+<GetConsumingEnumerable>d__9.MoveNext () [0x00000] in <filename unknown>:0 
  at Helios.Concurrency.DedicatedThreadPool+PoolWorker.RunThread () [0x00000] in <filename unknown>:0 
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0 

Linux version 4.2.0-42-generic (buildd@lgw01-55) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) ) #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016

Mono version 4.0.5.1

**Comment by Aaronontheweb** [comment]
@Alexcei88 everything ok here?

**Comment by Alexcei88** [comment]
@Aaronontheweb, I am using a library version 2.1.2. At first I will try to use the latest version 2.1.3.
